// Generates supabase/seed.sql from the app's store catalogue so the two never drift.
// Usage (Node 22.6+ strips the TypeScript types): node supabase/generate-seed.mjs
import { writeFileSync } from 'node:fs';
import { STORE_CATALOGUE } from '../frontend/src/lib/data/stores.ts';

const q = (v) => (v === undefined || v === null ? 'null' : typeof v === 'number' || typeof v === 'boolean' ? String(v) : `'${String(v).replaceAll("'", "''")}'`);

const lines = [
	'-- Generated by supabase/generate-seed.mjs from frontend/src/lib/data/stores.ts. Do not edit by hand.',
	'-- Store catalogue: stores, menus (with พิเศษ prices) and any promotions.',
	'-- Menu photos are mockups; store photos are served by the app from static/stores/.',
	'begin;'
];

for (const s of STORE_CATALOGUE) {
	lines.push(
		`insert into public.stores (id, zone, name, category, description, image_url, is_partner, tagline, fast_lane_minutes, is_open, rating, reviews_count, queue_minutes, lock) values (${[
			s.id, s.zone, s.name, s.category, s.description, s.imageUrl, s.isPartner, s.tagline, s.fastLaneMinutes, s.isOpen, s.rating, s.reviewsCount, s.queueMinutes, s.lock
		].map(q).join(', ')}) on conflict (id) do nothing;`
	);
	s.menuItems.forEach((m, i) => {
		lines.push(
			`insert into public.menu_items (id, store_id, name, price, special_price, original_price, description, image_url, category, is_available, is_popular, sort) values (${[
				m.id, m.storeId, m.name, m.price, m.specialPrice, m.originalPrice, m.description, m.imageUrl, m.category, m.isAvailable, !!m.isPopular, i
			].map(q).join(', ')}) on conflict (id) do nothing;`
		);
	});
	for (const p of s.promotions) {
		// Seeds run without a signed-in user, so the approval trigger keeps approved = true
		lines.push(
			`insert into public.promotions (store_id, kind, title, description, min_qty, discount, free_delivery, active, approved) values (${[
				p.storeId, p.kind, p.title, p.description, p.minQty, p.discount, p.freeDelivery, p.active, p.approved
			].map(q).join(', ')});`
		);
	}
}
lines.push('commit;', '');
writeFileSync(new URL('./seed.sql', import.meta.url), lines.join('\n'));
console.log(`seed.sql: ${STORE_CATALOGUE.length} stores, ${STORE_CATALOGUE.reduce((n, s) => n + s.menuItems.length, 0)} menu items, ${STORE_CATALOGUE.reduce((n, s) => n + s.promotions.length, 0)} promotions`);
