-- Generated by generate-loongnoom.mjs from loongnoom_square.json.
-- Apply 20261012000000_cb1_zone.sql in a separate transaction first.
-- Source: src/picture/ร้านลุงหนุ่ม/-1536x307.jpg; coffee options and CB1 confirmed by the user.
-- New store stays hidden/closed, matching team-console creation defaults.
-- Reapplying preserves team edits, availability, photos and visibility.
begin;
do $import$
declare
  stores_added integer;
  menus_added integer;
begin
  insert into public.stores
    (id, zone, name, category, description, image_url, logo_url, banner_url, is_partner, hidden, is_open, lock)
  values ('loongnoom-square', 'cb1', 'ลุงหนุ่ม Square', 'เครื่องดื่ม วาฟเฟิล ทาโกยากิ', 'เครื่องดื่ม Frozen กาแฟ ชา นมสดปั่น น้ำผลไม้ปั่น Butter Beer วาฟเฟิล และทาโกยากิ', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/drink.jpg', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/logo.jpg', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/waffles.jpg', false, true, false, 'อาคาร CB1')
  on conflict (id) do nothing;
  get diagnostics stores_added = row_count;

  insert into public.menu_items
    (id, store_id, name, price, description, image_url, category, is_available, sort)
  values
    ('loongnoom-square-macchiato-iced', 'loongnoom-square', 'Macchiato เย็น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 1),
    ('loongnoom-square-macchiato-blended', 'loongnoom-square', 'Macchiato ปั่น', 35, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 2),
    ('loongnoom-square-espresso-iced', 'loongnoom-square', 'Espresso เย็น', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 3),
    ('loongnoom-square-espresso-blended', 'loongnoom-square', 'Espresso ปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 4),
    ('loongnoom-square-mocca-iced', 'loongnoom-square', 'Mocca เย็น', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 5),
    ('loongnoom-square-mocca-blended', 'loongnoom-square', 'Mocca ปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 6),
    ('loongnoom-square-cappuccino-iced', 'loongnoom-square', 'Cappuccino เย็น', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 7),
    ('loongnoom-square-cappuccino-blended', 'loongnoom-square', 'Cappuccino ปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 8),
    ('loongnoom-square-latte-iced', 'loongnoom-square', 'Latte เย็น', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 9),
    ('loongnoom-square-latte-blended', 'loongnoom-square', 'Latte ปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 10),
    ('loongnoom-square-americano-iced', 'loongnoom-square', 'Americano เย็น', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 11),
    ('loongnoom-square-americano-blended', 'loongnoom-square', 'Americano ปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/coffee.png', 'กาแฟ', true, 12),
    ('loongnoom-square-frozen-blueberry', 'loongnoom-square', 'Blueberry & Cream Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-blueberry.png', 'Frozen', true, 13),
    ('loongnoom-square-frozen-cantaloupe', 'loongnoom-square', 'Cantaloupe & Cream Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-cantaloupe.png', 'Frozen', true, 14),
    ('loongnoom-square-frozen-fuji', 'loongnoom-square', 'Fuji Green Tea Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-fuji.png', 'Frozen', true, 15),
    ('loongnoom-square-frozen-white-malt', 'loongnoom-square', 'White Malt Cookies Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-white-malt.png', 'Frozen', true, 16),
    ('loongnoom-square-frozen-fuji-white-white', 'loongnoom-square', 'Fuji White White Honey Corn Flake Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-fuji-white-white.png', 'Frozen', true, 17),
    ('loongnoom-square-frozen-pink-milk', 'loongnoom-square', 'Pink Milk Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-pink-milk.png', 'Frozen', true, 18),
    ('loongnoom-square-frozen-corn-milk', 'loongnoom-square', 'Corn Milk Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-corn-milk.png', 'Frozen', true, 19),
    ('loongnoom-square-frozen-extra-milo', 'loongnoom-square', 'Extra Milo Raw Frozen', 50, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-extra-milo.png', 'Frozen', true, 20),
    ('loongnoom-square-frozen-x-tream', 'loongnoom-square', 'X-tream Caramel Milo Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-x-tream.png', 'Frozen', true, 21),
    ('loongnoom-square-frozen-black-white', 'loongnoom-square', 'Extra Black & White Cookies Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-black-white.png', 'Frozen', true, 22),
    ('loongnoom-square-frozen-pink-sky', 'loongnoom-square', 'Pink Sky Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-pink-sky.png', 'Frozen', true, 23),
    ('loongnoom-square-frozen-taro', 'loongnoom-square', 'Taro Milk & Cream Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-taro.png', 'Frozen', true, 24),
    ('loongnoom-square-frozen-elsa', 'loongnoom-square', 'Elsa Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-elsa.png', 'Frozen', true, 25),
    ('loongnoom-square-frozen-strawberry-yogurt', 'loongnoom-square', 'Strawberry Yogurt Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-strawberry-yogurt.png', 'Frozen', true, 26),
    ('loongnoom-square-frozen-anna', 'loongnoom-square', 'Anna Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-anna.png', 'Frozen', true, 27),
    ('loongnoom-square-frozen-mint', 'loongnoom-square', 'Mint Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-mint.png', 'Frozen', true, 28),
    ('loongnoom-square-frozen-vanilla', 'loongnoom-square', 'Vanilla Charcoal Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-vanilla.png', 'Frozen', true, 29),
    ('loongnoom-square-frozen-mocha', 'loongnoom-square', 'Mocha Cookie Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-mocha.png', 'Frozen', true, 30),
    ('loongnoom-square-frozen-banana', 'loongnoom-square', 'Banana & Cream Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-banana.png', 'Frozen', true, 31),
    ('loongnoom-square-frozen-strawberry', 'loongnoom-square', 'Strawberry & Cream Frozen', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/frozen-strawberry.png', 'Frozen', true, 32),
    ('loongnoom-square-black-widow', 'loongnoom-square', 'Black Widow', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/black-widow.png', 'Frozen', true, 33),
    ('loongnoom-square-chathai-frozen', 'loongnoom-square', 'Chathai Frozen', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/chathai-frozen.png', 'Frozen', true, 34),
    ('loongnoom-square-extra-cocoa', 'loongnoom-square', 'Extra Cocoa Aftershock Foam', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/extra-cocoa.png', 'Frozen', true, 35),
    ('loongnoom-square-strawberry-cream-cheese', 'loongnoom-square', 'Strawberry Cream Cheese', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/strawberry-cream-cheese.png', 'Frozen', true, 36),
    ('loongnoom-square-dsi', 'loongnoom-square', 'DSI', 45, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/dsi.png', 'Frozen', true, 37),
    ('loongnoom-square-brown-sugar-milk', 'loongnoom-square', 'บราวน์ชูการ์มิลค์', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/brown-sugar-milk.png', 'Frozen', true, 38),
    ('loongnoom-square-cs', 'loongnoom-square', 'CS', 50, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/cs.png', 'Frozen', true, 39),
    ('loongnoom-square-sticky-cocoa-teen', 'loongnoom-square', 'โกโก้นมเหนียว วัยทีน', 35, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/sticky-cocoa.png', 'โกโก้นมเหนียว', true, 40),
    ('loongnoom-square-sticky-cocoa-pro', 'loongnoom-square', 'โกโก้นมเหนียว วัยเก๋า', 40, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/sticky-cocoa.png', 'โกโก้นมเหนียว', true, 41),
    ('loongnoom-square-butter-beer-original', 'loongnoom-square', 'Butter Beer Original', 35, 'ไม่มีส่วนผสมแอลกอฮอล์ ตามป้ายร้าน', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/butter-beer-original.png', 'Butter Beer', true, 42),
    ('loongnoom-square-butter-beer-slytherin', 'loongnoom-square', 'Butter Beer Slytherin (Apple)', 40, 'ไม่มีส่วนผสมแอลกอฮอล์ ตามป้ายร้าน', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/butter-beer-slytherin.png', 'Butter Beer', true, 43),
    ('loongnoom-square-butter-beer-gryffindor', 'loongnoom-square', 'Butter Beer Gryffindor (Strawberry)', 40, 'ไม่มีส่วนผสมแอลกอฮอล์ ตามป้ายร้าน', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/butter-beer-gryffindor.png', 'Butter Beer', true, 44),
    ('loongnoom-square-butter-beer-ravenclaw', 'loongnoom-square', 'Butter Beer Ravenclaw (Blue Hawaii)', 40, 'ไม่มีส่วนผสมแอลกอฮอล์ ตามป้ายร้าน', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/butter-beer-ravenclaw.png', 'Butter Beer', true, 45),
    ('loongnoom-square-butter-beer-hufflepuff', 'loongnoom-square', 'Butter Beer Hufflepuff (Lychee)', 40, 'ไม่มีส่วนผสมแอลกอฮอล์ ตามป้ายร้าน', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/butter-beer-hufflepuff.png', 'Butter Beer', true, 46),
    ('loongnoom-square-butter-beer-blueberry', 'loongnoom-square', 'Butter Beer Blueberry', 40, 'ไม่มีส่วนผสมแอลกอฮอล์ ตามป้ายร้าน', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/butter-beer-blueberry.png', 'Butter Beer', true, 47),
    ('loongnoom-square-milk-caramel', 'loongnoom-square', 'นมสดคาราเมลปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/milk-smoothies.png', 'นมสดปั่น', true, 48),
    ('loongnoom-square-milk-honey', 'loongnoom-square', 'นมสดน้ำผึ้งปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/milk-smoothies.png', 'นมสดปั่น', true, 49),
    ('loongnoom-square-milk-chocolate', 'loongnoom-square', 'นมสดช็อกโกแลตปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/milk-smoothies.png', 'นมสดปั่น', true, 50),
    ('loongnoom-square-smoothie-coconut', 'loongnoom-square', 'มะพร้าวปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/smoothie-coconut.png', 'น้ำผลไม้ปั่น', true, 51),
    ('loongnoom-square-smoothie-orange', 'loongnoom-square', 'น้ำส้มปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/fruit-smoothies.png', 'น้ำผลไม้ปั่น', true, 52),
    ('loongnoom-square-smoothie-watermelon', 'loongnoom-square', 'น้ำแตงโมปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/fruit-smoothies.png', 'น้ำผลไม้ปั่น', true, 53),
    ('loongnoom-square-smoothie-strawberry', 'loongnoom-square', 'น้ำสตรอเบอร์รี่ปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/fruit-smoothies.png', 'น้ำผลไม้ปั่น', true, 54),
    ('loongnoom-square-smoothie-pineapple', 'loongnoom-square', 'น้ำสับปะรดปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/fruit-smoothies.png', 'น้ำผลไม้ปั่น', true, 55),
    ('loongnoom-square-smoothie-carrot', 'loongnoom-square', 'น้ำแครอทปั่น', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/fruit-smoothies.png', 'น้ำผลไม้ปั่น', true, 56),
    ('loongnoom-square-smoothie-mixed-fruit', 'loongnoom-square', 'น้ำผลไม้รวมปั่น', 35, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/fruit-smoothies.png', 'น้ำผลไม้ปั่น', true, 57),
    ('loongnoom-square-smoothie-strawberry-yogurt', 'loongnoom-square', 'สตรอเบอร์รี่โยเกิร์ต', 30, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/smoothie-strawberry-yogurt.png', 'น้ำผลไม้ปั่น', true, 58),
    ('loongnoom-square-soda-lychee', 'loongnoom-square', 'ลิ้นจี่โซดา', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/italian-sodas.png', 'อิตาเลี่ยนโซดา', true, 59),
    ('loongnoom-square-soda-blue-hawaii', 'loongnoom-square', 'บลูฮาวายโซดา', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/italian-sodas.png', 'อิตาเลี่ยนโซดา', true, 60),
    ('loongnoom-square-soda-blueberry', 'loongnoom-square', 'บลูเบอร์รี่โซดา', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/italian-sodas.png', 'อิตาเลี่ยนโซดา', true, 61),
    ('loongnoom-square-soda-strawberry', 'loongnoom-square', 'สตรอเบอร์รี่โซดา', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/italian-sodas.png', 'อิตาเลี่ยนโซดา', true, 62),
    ('loongnoom-square-thai-tea', 'loongnoom-square', 'ชาเย็น', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/thai-tea.png', 'ชาและนม', true, 63),
    ('loongnoom-square-cocoa', 'loongnoom-square', 'โกโก้', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/cocoa.png', 'ชาและนม', true, 64),
    ('loongnoom-square-milk-tea', 'loongnoom-square', 'ชานม', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/milk-tea.png', 'ชาและนม', true, 65),
    ('loongnoom-square-green-tea', 'loongnoom-square', 'ชาเขียว', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/green-tea.png', 'ชาและนม', true, 66),
    ('loongnoom-square-white-malt', 'loongnoom-square', 'ไวท์มอลต์', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/white-malt.png', 'ชาและนม', true, 67),
    ('loongnoom-square-black-tea', 'loongnoom-square', 'ชาดำ', 25, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/black-tea.png', 'ชาและนม', true, 68),
    ('loongnoom-square-waffle-banana', 'loongnoom-square', 'วาฟเฟิล กล้วยหอม', 12, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/waffle-banana.png', 'วาฟเฟิล', true, 69),
    ('loongnoom-square-waffle-almond', 'loongnoom-square', 'วาฟเฟิล อัลมอนด์', 12, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/waffle-almond.png', 'วาฟเฟิล', true, 70),
    ('loongnoom-square-waffle-chocolate', 'loongnoom-square', 'วาฟเฟิล ช็อกโกแลต', 12, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/waffle-chocolate.png', 'วาฟเฟิล', true, 71),
    ('loongnoom-square-waffle-strawberry', 'loongnoom-square', 'วาฟเฟิล สตรอเบอร์รี่', 12, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/waffle-strawberry.png', 'วาฟเฟิล', true, 72),
    ('loongnoom-square-waffle-blueberry', 'loongnoom-square', 'วาฟเฟิล บลูเบอร์รี่', 12, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/waffle-assortment.png', 'วาฟเฟิล', true, 73),
    ('loongnoom-square-waffle-butter-milk', 'loongnoom-square', 'วาฟเฟิล เนยนม', 12, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/waffle-assortment.png', 'วาฟเฟิล', true, 74),
    ('loongnoom-square-waffle-pandan', 'loongnoom-square', 'วาฟเฟิล ใบเตย', 12, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/waffle-assortment.png', 'วาฟเฟิล', true, 75),
    ('loongnoom-square-takoyaki-mussel-1', 'loongnoom-square', 'ทาโกยากิ หอยแมลงภู่ (1 ลูก)', 7, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 76),
    ('loongnoom-square-takoyaki-mussel-3', 'loongnoom-square', 'ทาโกยากิ หอยแมลงภู่ (3 ลูก)', 20, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 77),
    ('loongnoom-square-takoyaki-squid-1', 'loongnoom-square', 'ทาโกยากิ ปลาหมึก (1 ลูก)', 7, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 78),
    ('loongnoom-square-takoyaki-squid-3', 'loongnoom-square', 'ทาโกยากิ ปลาหมึก (3 ลูก)', 20, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 79),
    ('loongnoom-square-takoyaki-sausage-1', 'loongnoom-square', 'ทาโกยากิ ไส้กรอก (1 ลูก)', 7, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 80),
    ('loongnoom-square-takoyaki-sausage-3', 'loongnoom-square', 'ทาโกยากิ ไส้กรอก (3 ลูก)', 20, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 81),
    ('loongnoom-square-takoyaki-crab-1', 'loongnoom-square', 'ทาโกยากิ ปูอัด (1 ลูก)', 7, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 82),
    ('loongnoom-square-takoyaki-crab-3', 'loongnoom-square', 'ทาโกยากิ ปูอัด (3 ลูก)', 20, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 83),
    ('loongnoom-square-takoyaki-salmon-1', 'loongnoom-square', 'ทาโกยากิ ปลาแซลมอน (1 ลูก)', 7, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 84),
    ('loongnoom-square-takoyaki-salmon-3', 'loongnoom-square', 'ทาโกยากิ ปลาแซลมอน (3 ลูก)', 20, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 85),
    ('loongnoom-square-takoyaki-tobiko-1', 'loongnoom-square', 'ทาโกยากิ ไข่กุ้ง (1 ลูก)', 7, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 86),
    ('loongnoom-square-takoyaki-tobiko-3', 'loongnoom-square', 'ทาโกยากิ ไข่กุ้ง (3 ลูก)', 20, '', 'https://pguhzjtdwgualqeqzleu.supabase.co/storage/v1/object/public/store-banners/loongnoom-square/menu/takoyaki.png', 'ทาโกยากิ', true, 87)
  on conflict (id) do nothing;
  get diagnostics menus_added = row_count;

  if stores_added > 0 or menus_added > 0 then
    insert into public.admin_log (actor_name, action, target_type, target_id, target_label, detail)
    values ('SQL import (Supabase CLI)', 'STORE_IMPORTED', 'store', 'loongnoom-square', 'ลุงหนุ่ม Square',
      jsonb_build_object('source', 'src/picture/ร้านลุงหนุ่ม/-1536x307.jpg', 'stores_added', stores_added,
        'menus_added', menus_added, 'location_confirmed', 'CB1', 'coffee_options', 'iced/blended'));
  end if;
end
$import$;
commit;
